### PR TITLE
Update for Symfony ~2.6

### PR DESCRIPTION
**Pull request by navitronic**
We've been using your library (via [kphoen/doctrine-state-machine-bundle](https://github.com/K-Phoen/DoctrineStateMachineBundle)) and as a push for getting ready for Symfony 2.8 / 3.0, we've been trying to eliminate all deprecated warnings in our code and the third party libraries that we use.

This PR represents the changes that were required for preventing this library from causing the warnings. It represents a culmination of the code in #90, #85 and #79 (and maybe some extra too)

In addition, I have made the following composer related changes:

- I have also removed the `composer.lock` file, as it's generally [superfluous](https://getcomposer.org/doc/02-libraries.md#lock-file) in a library designed for consumption by others.
- I have updated the `composer.json` requirements for Symfony versions to be `~2.6`

The required changes in symfony versions means that this PR has BC compatibility issues for people using it in projects with older versions of Symfony, so in the strictest semver terms, it would require a new major release.

If you have any issues, please let me know. Would love to see the deprecation issues addressed.

Thanks. :+1:

### CODE REVIEW

**Comment by phillipsnick** [comment]
Thanks for these :+1:

**Comment by yohang** [comment]
Merged, thanks !

**Comment by tortuetorche** [comment]
Cool, do you plan to create a `1.1` branch or a `1.1.0` tag for these changes?

**Comment by yohang** [comment]
There will be a 1.1.0 tag, let say, this week, but no 1.1 branch as the master branch is 1.1 (see branch-alias in composer.json / packagist).

I'll create a 1.1 branch when working on a 1.2 or 2.0 version.

**Comment by tortuetorche** [comment]
@yohang Many thanks :clap: !

**Pull request merged**
