### PR TITLE
Drop support for PHP <7.2

### LINKED ISSUE #148: Let's  update The PHPUnit？
PHPUnit 4 already Support ended,  update  PHPUnit to 8 can be better. And we can Support PHP7

### PR DESCRIPTION
**Pull request by alpaxo**
Bump phpunit version to 8.5
Fix tests for newer phpunit
Remove outdated PHP versions from .travis.yml

Closes #148 #146

### CODE REVIEW

**Comment by alpaxo** [comment]
Incompatible with symfony event-dispatcher "Calling the "%s::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead."

**Comment by cmizzi** [comment]
@alpaxo Why don't just reverse the arguments ? The version would be `^4.3|^5.0`.

**Comment by hiteule** [comment]
@alpaxo I'm interested by your PR.
You can resolve the event-dispatcher incompatibility by using the `LegacyEventDispatcherProxy` like this :
```
if (class_exists(LegacyEventDispatcherProxy::class)) {
    $this->dispatcher = LegacyEventDispatcherProxy::decorate($this->dispatcher);
}
```

or/and :

```
if (class_exists(LegacyEventDispatcherProxy::class)) {
    $this->dispatcher->dispatch(new StateMachineEvent($this), FiniteEvents::SET_INITIAL_STATE);
} else {
    // Dispatch with EventDispatcher < 4.3
    $this->dispatcher->dispatch(FiniteEvents::SET_INITIAL_STATE, new StateMachineEvent($this));
}
```

**Comment by alpaxo** [comment]
@hiteule it seems this repo is abandoned. I have made a working fork for symfony5/laravel7 which is located at https://github.com/alpaxo/finite3 you can use it if you want. 

I am waiting for https://github.com/yohang/Finite/pull/151 to be merged and after that i will be able to create another PR with support for recent php/phpunit/symfony

**Pull request closed without merging**
