### PR TITLE
Refactored StateMachine to reduce complexity a bit

### PR DESCRIPTION
**Pull request by RonRademaker**
Hi,

I refactored the events part of the StateMachine a bit to address part of #105

### CODE REVIEW

**Comment by phillipsnick** [comment]
Nice! Any reason the `dispatchTransitionEvent` is private over protected though?

I extend the StateMachine on one project to add some functionality.

**Comment by RonRademaker** [comment]
Making methods and properties private allows you to refactor or change things in the future without breaking backwards compatibility. Unless there's a use case that'd require making the method protected I'd say it's good practice to make anything (that is not part of the public API of course) private.

**Comment by phillipsnick** [comment]
Ah ok, thanks for the info :+1:

**Comment by yohang** [comment]
Seems good, thanks !

**Pull request merged**
