### PR TITLE
Event Params

### PR DESCRIPTION
**Pull request by Padam87**
It would be useful to be able to pass params to transition events. See the doc for more details

| Q | A |
| -------------  |------|
| Test Pass? | y     |
| License      | MIT |

### CODE REVIEW

**Comment by Padam87** [comment]
@yohang ping

**Comment by selossevianney** [comment]
This is what I need and I'm not the only one. Why did Yohang never merged this PR? Go ahead @yohang  You'll do the right thing :+1:

**Comment by Padam87** [comment]
I was thinking about creating a fork for this lib, and start implementing new stuff there. @yohang doesn't seem to be working on this anymore.

**Comment by selossevianney** [comment]
Too bad. Stop thinking, do it :)

**Comment by yohang** [comment]
I'll probably merge your PR today, but I’m thinking to a more flexible way to define the `OptionsResolver`.

Here is what I'd prefer for the resolver :
  * Ability to be defined outside of config (for YAML configs)
  * Ability to be altered

Thanks for the good work !

**Comment by Padam87** [comment]
Sorry, no more changes from my part... It's been more than a year, if I change this again it will be another year. Merge it, and the yaml config should be done separately.

**Comment by yohang** [comment]
I know, and agree, I'll do the work, I can't ask you to do it after 1 year !

**Comment by yohang** [comment]
Closing as I continue your work in #97.

Thanks for making it and sorry for not being available :(

**Pull request closed without merging**
